### ISSUE TITLE
Feature Request: Move Encounter Info with Page Scrolling

### ISSUE THREAD

**Issue by Surael** [jbarzilai/5e-monsters#22] opened 2016-12-07 01:50 UTC
Would be nice if the current group / encounter info was always visible while scrolling through a long list of monsters, instead of having to go back up to the top of the page every time you want to look at it or adjust something.

**Comment by jbarzilai** [comment] 2016-12-07 02:27
Definitely planning on doing this.  This is a duplicate of #8 though so I'm going to close this.  If you think you are requesting something different, then feel free to reopen it.

**Closed as completed by jbarzilai** 2016-12-07 02:27 UTC
Labels: duplicate
